import React from 'react';
import { storiesOf, action } from '@kadira/storybook';
import JSONTree from './index';
import * as DotObject from 'dot-object';

export default class JEHarness extends React.Component {
  constructor(props) {
    super(props);
    //this.state = {
    //  hunter: {
    //    name: "hunter",
    //    age: 26,
    //    random: {
    //      nested: true,
    //      brother: "Theo"
    //    },
    //    blank: {}
    //  }
    //}

    this.state = {
      "AccountSummaryBeanList": [
        {
          "cardBean": {
            "memberSince": "CARD MEMBER SINCE 2013",
            "footNote": "This is not a billing statement.",
            "simplyCashPlusCard": false,
            "employeeControlEligible": false,
            "EPDPDefaultValues": "",
            "cancelledCardFlag": false,
            "cardAccountStatus": "Active",
            "plumCardFlag": false,
            "cmFirstName": "HUNTER",
            "smallCardArtImgLink": "https://online.americanexpress.com/myca/shared/summary/cardasset/images/NUS000000096.gif",
            "cardUserRole": "BASIC",
            "nonUSCardURL": "",
            "cmName": "Hunter S Bacot",
            "accountNumber": "-51007",
            "zipPostalCode": "11206",
            "nonUSCard": false,
            "DPMessage": "",
            "EPMessage": "",
            "cardTypePlum": false,
            "EPDPLineMessageLarge": "",
            "DPMessageLarge": "",
            "corporateCardFlag": false,
            "cardSortedIndex": "0",
            "cardArtImgLink": "https://online.americanexpress.com/myca/shared/summary/cardasset/images/NUS000000096_160X101_STRAIGHT.gif",
            "cardProductName": "Platinum Card®",
            "omnitureProductCode": "US:137",
            "encryptedAccountNumber": "O5C1l-wfCI7BExwokGSyoVem9EmSsrX0_kjdBdJAehk=",
            "earlyDeferPayLink": "",
            "cardTypeFlag": "CCSG",
            "EPDPLineMessage": "",
            "productCode": "137",
            "dollar": "$",
            "EPMessageLarge": "",
            "goldenGooseFlag": false
          },
          "acctHubLinksPageBean": {
            "requestRefundLink": "#",
            "showUpdateContactInfoLink": false,
            "currentAPREnabledFlag": false,
            "showRequestRefundLink": false,
            "currentAPRLink": "#",
            "showManageAcctAlertsLink": true,
            "payChargesOverTimeEnableFlag": true,
            "manageAcctAlertsLinkLabel": "Manage Account Alerts",
            "addCardforEmployeesLinkLabel": "",
            "yearEndSummaryLinkUrl": "#",
            "moreOptionsLinkLabel": "More Options",
            "showViewCreditScoreLink": true,
            "yearEndSummaryLinkLabel": "",
            "paymentSummaryLabel": "Payment Activity",
            "disputeOrInquireAbtChargeLink": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_disputes&intlink=us-ser-soa-accnthub-fin-disputesaboutacharge&entryChannel=ESTSM&locale=en_US&BPIndex=1&sorted_index=0",
            "viewCardMemberAgreementLink": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_pcm&sorted_index=0&intlink=us-ser-soa-accnthub-fin-cardagreement",
            "useFulLinkRowButtonLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&sorted_index=0&BPIndex=0&mycaTrend=YES&intlink=us-ser-soa-accnthub-serv-viewyearendsummarytrends",
            "addOthersToYourAccountLinkUrl": "https://www304.americanexpress.com/personal-card-application/supplementary/generic/apply/45263-9-0?intlink=us-ser-soa-accnthub-addsomeonetoyouraccount",
            "checkSpendingAbilityLinkLabel": "Check Spending Power",
            "searchPlacesToGoLinkUrl": "#",
            "viewCreditScoreLabel": "View FICO&reg; Score",
            "currentAPRLabel": "",
            "replaceLostDamagedCardLinkLabel": "Replace Lost/Damaged Card",
            "showSearchPlacesToGoLink": false,
            "updateContactInfoLinkLabel": "",
            "showPaymentSummaryLink": false,
            "disputeOrInquireAbtChargeLabel": "Dispute/Inquire About a Charge",
            "viewCardMemberAgreementLabel": "Card Agreement",
            "useFulLinkRowTextLabel": "Year-End Summary is here! Now including new features.",
            "addCardforEmployeesLinkUrl": "#",
            "moreOptionsLinkUrl": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_home&Face=en_US&intlink=us-ser-soa-accnthub-serv-moreoptions",
            "requestRefundLabel": "",
            "viewCreditScoreLink": "https://online.americanexpress.com",
            "showSeeAllCardBenefitsLink": false,
            "viewCardMemberAgreementEnabledFlag": true,
            "showAddCardsForEmployeesLink": false,
            "showCheckSpendingAbilityLink": true,
            "useFulLinkRowButtonLabel": "View Now",
            "paymentSummaryLink": "https://online.americanexpress.com/myca/onlinepayment/us/paymenthistory.do?request_type=authreg_CardPayments&Face=en_US&sorted_index=0&intlink=us-ser-soa-accnthub-fin-paymentsummary",
            "seeAllCardBenefitsLinkUrl": "#",
            "showYearEndSummaryLink": false,
            "addOthersToYourAccountLinkLabel": "Add Someone to Your Account",
            "seeAllCardBenefitsLinkLabel": "",
            "searchPlacesToGoLinkLabel": "",
            "showReplaceLostDamagedCardLink": true,
            "requestRefundEnabledFlag": false,
            "showMoreOptionsLink": true,
            "replaceLostDamagedCardLinkUrl": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_ocr&sorted_index=0&source=janus&intlink=us-ser-soa-accnthub-serv-replacelostdamangedcard",
            "paymentSummaryEnabledFlag": true,
            "updateContactInfoLinkUrl": "#",
            "showAddOthersToYourAccountLink": true,
            "showGoPaperlessLink": true,
            "payChargesOverTimeLabel": "Pay Charges Over Time",
            "goPaperlessLinkLabel": "Go Paperless",
            "disputeOrInquireAbtChargeFlag": true,
            "headerLabel": "Useful Links",
            "lastLogonLabel": "Your Last Log In:",
            "lastLogonDate": "May 18, 2016 @ 3:51 PM ET"
          },
          "limitsBean": {
            "increaseLineOfCreditLink": "#",
            "availableCredit": " limit",
            "showSpendingLimitsData": false,
            "suppLimitsEnabled": false,
            "avlCrdtOffscrnTxt": "Your card has No pre-set spending limit",
            "nsplFlag": false,
            "suppIndicator": false,
            "availableCreditToolTipFlag": false,
            "needToSpendAboveCreditLinkLabel": "",
            "creditLimitLabel": "Credit Limit",
            "availableCreditLbl": "No pre-set spending",
            "increaseLineOfCreditLinkLabel": "",
            "limitsMsgFlag": false,
            "accessOtherCreditToolLink": "",
            "currentAboveLimitToolTipFlag": false,
            "needToSpendMoreLink": "",
            "accessOtherCreditToolLinkLabel": "",
            "limitMsgTooltip": "This amount is updated in real time and reflects all account activity, including outstanding authorizations. Since Recent Activity is updated nightly, it may not match this amount.",
            "transactionLimit": "Not Available",
            "limitsErrorMsgFlag": false,
            "totalCreditLimit": "Not Available",
            "noPreSetSpendingToolTip": "No Pre-Set Spending Limit does not mean unlimited spending. Purchasing power adjusts with the use of the account, payment history, credit record, and financial resources known to us, and other factors."
          },
          "financialBean": {
            "paymentsURL": "https://online.americanexpress.com/myca/onlinepayment/us/paymentcenter.do?request_type=authreg_PayBill&Face=en_US&sorted_index=0&intlink=us-ser-soa-accnthub-fin-makepayment",
            "postTransactionMsg": "",
            "paymentDueDateMsg": "Payment not required at this time",
            "corporateFootNote": "",
            "statementBalanceLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=1&sorted_index=0&intlink=us-ser-soa-accnthub-fin-statementbalance",
            "statementBalanceLbl": "Statement Balance",
            "recentPaymentsAndCredits": "$0.00",
            "payOverTimeUsefulLinkEligible": false,
            "currentBalanceLabel": "Payment Due",
            "currentBalanceAmtHeader": "0",
            "seeAllRecentActivityLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=0&sorted_index=0&intlink=us-ser-soa-accnthub-trans-viewrecentactivity",
            "postTransactionErrorFlag": "false",
            "interestCalcLbl": "See APR History & Interest Charge Calculation",
            "stmtBalanceDateRange": "",
            "pendingChargesToolTip": "Pending Charges are purchases or pre-authorizations that haven't been posted to your account yet. For example, a hotel may pre-authorize an amount at check in, then submit the final charge at check out. Only the final charge will increase your Total Balance or accrue interest.",
            "hvolCard": false,
            "recentsPmtCreditsLbl": "Recent Payments & Credits",
            "paymentMsg": "",
            "transactionPageBeanList": [
              {
                "creditTransaction": false,
                "transactionAmount": "11.75",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161380603318656&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Mon, May 16",
                "transactionDescription": "DOS TOROS TAQUERIA NEW YORK NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "17.49",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161380603420344&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Mon, May 16",
                "transactionDescription": "SEAMLSS BOMBAY KITCH8775857878 IL",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "87.17",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161380602180663&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Mon, May 16",
                "transactionDescription": "TOMS.COM USD LOS ANGELES CA",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "7.50",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161370587849151&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "CUP BROOKLYN NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "8.00",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161360572777341&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "DANNY'S PIZZERIA II BROOKLYN NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "150.00",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161350543741955&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "PAYPAL *BK FLEA BK F4029357733 NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "5.08",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161350546729997&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "PUDGE KNUCKLES BROOKLYN NY",
                "creditedTrnxIndicator": ""
              }
            ],
            "goToOnlineStatmentLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=1&sorted_index=0&intlink=us-ser-soa-accnthub-trans-currentstatement",
            "currentBalance": "$0.00",
            "outstandingAmtDecimal": "21",
            "recentActivityLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=0&sorted_index=0&intlink=us-ser-soa-accnthub-fin-recentactivity",
            "currentBalanceDot": ".",
            "currentBalanceAmtCents": "00",
            "postTrnxHeaderCountText": "1 - 7 of 9",
            "nextStmtClosingDate": " (Next Closing Date Jun 8)",
            "outstandingAmtDollar": "$",
            "displayPaymentReminderMsg": true,
            "pendingChargesFlag": true,
            "postTransText": "Transactions",
            "recentPaymentAndCreditsToolTip": "This amount includes any payments, returned payments and credits received since your most recent billing statement. Activity in the last 24 hours may not be reflected.",
            "totalTransactionCount": 9,
            "statementBalanceToolTip": "This amount is the New Balance showing on your most recent billing statement. This balance does not include any new payments, returned payments, credits or transactions made after the last closing date.  No amounts under dispute have been deducted from this balance.",
            "displayPaymentDueDate": false,
            "currentBalanceDollar": "$",
            "currentBalanceToolTip": "Payment is due upon receipt of your statement. We suggest you pay by the Please Pay By date.",
            "outStandingBalanceToolTip": "This amount is the full balance on your account adjusted for payments, returned payments, applicable credits and transactions since your last statement closing date. No amounts under dispute have been deducted from this balance. Activity in the last 24 hours may not be reflected.",
            "recentPaymentsLink": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&applyFilter=true&transactionTypeFilter=4,5&intlink=us-ser-soa-accnthub-fin-recentpaymentsandcredits",
            "minPaymentDueToolTip": "",
            "postedTransactionToolTip": "Charges, payments, and credits since your statement closed.",
            "recentActivityDateRange": "May 10 — Today (Next Closing Date Jun 8)",
            "paymentsLabel": "Make Payment",
            "downloadStatement": "https://online.americanexpress.com/myca/statementimage/us/welcome.do?Face=en_US&request_type=authreg_StatementCycles&sorted_index=0&intlink=us-ser-soa-accnthub-fin-billingstatements",
            "paymentReminderMsg": "",
            "recentActivityLbl": "Recent Activity",
            "suppIndicator": false,
            "pleasePayByToolTip": "",
            "interestCalcURL": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=1&sorted_index=0&openLayer=A",
            "negativeCurrBalText": "",
            "smallChnlPmtDueDate": "Not Available",
            "recentActivityDate": " since May 10",
            "paymentDueDate": "",
            "currentStatementLbl": "Current Statement",
            "corporateFootNoteSuperScript": "",
            "displayPayoverTimeLink": false,
            "simplyCashBizOverLimitIndicator": false,
            "outstandingBalance": "$330.21",
            "paymentAmt": "",
            "recentCharges": "$330.21",
            "requestRefundEnabledFlag": false,
            "currentBalOffscrnTxt": "Your card has a Payment Due of 0 dollars and 00 cents ",
            "statementBalance": "$0.00",
            "viewAllRecentActivityLbl": "View All Recent Activity",
            "displayCurrentAPRLinkFlag": false,
            "currentBalanceLblForShowEqnToolTip": "Payment is due upon receipt of your statement. We suggest you pay by the Please Pay By date.",
            "outstandingBalanceLbl": "Total Balance",
            "billingStatementsLbl": "Billing Statements",
            "currentBalanceLblForShowBalanceEqn": "Payment Due",
            "recentActivityToolTip": "This amount includes all charges, excluding credits, payments, and returned payments, since your most recent billing statement. Activity in the last 24 hours may not be reflected.",
            "outstandingAmtHeader": "330",
            "displayDisputeMsg": false,
            "errorFlag": false,
            "notificationMsg": "",
            "transactions": [
              {
                "creditTransaction": false,
                "transactionAmount": "11.75",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161380603318656&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Mon, May 16",
                "transactionDescription": "DOS TOROS TAQUERIA NEW YORK NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "17.49",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161380603420344&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Mon, May 16",
                "transactionDescription": "SEAMLSS BOMBAY KITCH8775857878 IL",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "87.17",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161380602180663&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Mon, May 16",
                "transactionDescription": "TOMS.COM USD LOS ANGELES CA",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "7.50",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161370587849151&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "CUP BROOKLYN NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "8.00",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161360572777341&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "DANNY'S PIZZERIA II BROOKLYN NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "150.00",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161350543741955&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "PAYPAL *BK FLEA BK F4029357733 NY",
                "creditedTrnxIndicator": ""
              },
              {
                "creditTransaction": false,
                "transactionAmount": "5.08",
                "transactionETDURL": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=0&BPIndex=0&openLayer=PE&etdRocId=320161350546729997&intlink=us-ser-soa-accnthub-trans-postedtransaction",
                "transactionDate": "Sat, May 14",
                "transactionDescription": "PUDGE KNUCKLES BROOKLYN NY",
                "creditedTrnxIndicator": ""
              }
            ]
          },
          "goldenGooseFlag": false,
          "membershipRewardsBean": {
            "usePointsForInvestWithRewardsLink": "https://rewards.americanexpress.com/myca/loyalty/us/rewards/rw/csb/iwrhome?client=AccountHub",
            "loyaltyEarninginstrumentListCount": 0,
            "usePointsForShoppingLabel": "Shopping",
            "eligibleForDPM": false,
            "ctaButtonLargeLink": "#",
            "errorFlag": false,
            "plumSupp": false,
            "multiLnkIndActiveAccntIndicator": false,
            "usePointsForGiftCardsLabel": "Gift Cards",
            "loyaltyAccountNumberLabel": "Program Number",
            "noLoyaltyCTALink": "#",
            "mrDataAvailableFlag": true,
            "availablePointsLink": "https://rewards.americanexpress.com/myca/loyalty/us/rewards/mracctmgmt/acctsumm?request_type=authreg_mr&Face=en_US&mrk=02EE056B435FA8B815C09B50E90EF0C8&intlink=us-ser-soa-accnthub-rewards-points",
            "pointBalanceLabel": "Available Points",
            "noLoyaltyCTALabel": "",
            "usePointsForInvestWithRewardsLabel": "Invest with Rewards",
            "moreInfoLinkLrgURL": "#",
            "pointBalance": "0",
            "openRebateCardWithNoCta": false,
            "moreInfoLinkLrgTxt": "",
            "membershipRewardsProgNameLink": "https://www.membershiprewards.com?intlink=us-ser-soa-accnthub-rewards-MR",
            "programName": "Membership Rewards®",
            "loyaltyAccountNumber": "1M11310395",
            "ctaButtonLabel": "",
            "errorMessage1": "Sorry about that!",
            "usePointsForTravelLink": "https://rewards.americanexpress.com/myca/loyalty/us/catalog/travelhub?viewfullsite=y&mrlinknav=header-travel&intlink=us-ser-soa-accnthub-rewards-travel",
            "errorMessage2": "It doesn't happen often, but your Rewards information is unavailable.",
            "usePointsForChargesLabel": "Your Charges",
            "errorMessage3": "Please try again later.",
            "loyaltyResponseCode": "LAI0000",
            "jetBlueCardProductFlag": false,
            "goldenGooseMREligibleFlag": true,
            "freedomPassCardProduct": false,
            "loyaltyProgramType": "REWARD_PROGRAMS",
            "usePointsForChargesLink": "https://rewards.americanexpress.com/myca/loyalty/us/rewards/edrredemption/rocs/getedreligiblerocs?request_type=authreg_mr&Face=en_US&sorted_index=0&intlink=us-ser-soa-accnthub-rewards-yourcharges",
            "medallionStatusToolTip": "",
            "nonMRFlag": false,
            "buckChargeCard": false,
            "usePointsForShoppingLink": "https://www01.extra.americanexpress.com/FrontPage.aspx?noredir=true&mrlinknav=header-shopping&intlink=us-ser-soa-accnthub-rewards-shopping",
            "rewardsForPlumPresent": false,
            "buckLendingCard": false,
            "loyaltyTier": "PR",
            "usePointsLabel": "Use Points",
            "loyaltyFamily": "MembershipRewards",
            "usePointsForGiftCardsLink": "https://rewards.americanexpress.com/myca/loyalty/us/catalog/giftcardhub?viewfullsite=y&mrlinknav=header-giftcards&intlink=us-ser-soa-accnthub-rewards-giftcards",
            "pointsYTDLabel": "",
            "loyaltyOfferLink": "http://www.membershiprewards.com/homepage.aspx?intlink=CMO_newSOA_MR",
            "noLoyaltyFlag": false,
            "waysToUsePointsText": "Ways To Use Points",
            "loyaltyStatus": "",
            "moreInfoLinkSmlURL": "#",
            "usePointsForTravelLabel": "Travel",
            "moreInfoLinkSmlTxt": "",
            "pendingPointsMobLink": "https://rewards.americanexpress.com/myca/loyalty/mobl/us/redeem/Landing.do?mrk=02EE056B435FA8B815C09B50E90EF0C8&intlink=us-ser-soa-accnthub-rewards-points",
            "loyaltyStatusFlag": false,
            "noLoyaltyMessage1": "",
            "noLoyaltyMessage2": "",
            "plumBasic": false,
            "ctaButtonLargeLabel": "",
            "ctaButtonLink": "#"
          },
          "acctLevelMsgPageBean": {
            "incomeCaptureMsgFlag": false,
            "sixtyDaysPastDueMessage": "",
            "openCardFlag": false,
            "repetitiveNFCFlag": false,
            "warnMsgFlag": false,
            "nfcFlag": false,
            "displaySixtyDaysPastDueMsg": false,
            "displayOffersTab": false,
            "acctLevelNFCMessage": ""
          }
        },
        {
          "cardBean": {
            "memberSince": "CARD MEMBER SINCE 2013",
            "footNote": "This is not a billing statement.",
            "simplyCashPlusCard": false,
            "employeeControlEligible": false,
            "EPDPDefaultValues": "",
            "cancelledCardFlag": false,
            "cardAccountStatus": "Active",
            "plumCardFlag": false,
            "cmFirstName": "HUNTER",
            "smallCardArtImgLink": "https://online.americanexpress.com/myca/shared/summary/cardasset/images/NUS000000067.gif",
            "cardUserRole": "BASIC",
            "nonUSCardURL": "",
            "cmName": "Hunter S Bacot",
            "accountNumber": "-92000",
            "zipPostalCode": "11206",
            "nonUSCard": false,
            "DPMessage": "",
            "EPMessage": "",
            "cardTypePlum": false,
            "EPDPLineMessageLarge": "",
            "DPMessageLarge": "",
            "corporateCardFlag": false,
            "cardSortedIndex": "1",
            "cardArtImgLink": "https://online.americanexpress.com/myca/shared/summary/cardasset/images/NUS000000067_160X101_STRAIGHT.gif",
            "cardProductName": "Gold Delta SkyMiles®",
            "omnitureProductCode": "US:113",
            "encryptedAccountNumber": "O5C1l-wfCI7BExwokGSyoWHT-ojrc7B6-acLbstTUYM=",
            "earlyDeferPayLink": "",
            "cardTypeFlag": "CCSG",
            "EPDPLineMessage": "",
            "productCode": "113",
            "dollar": "$",
            "EPMessageLarge": "",
            "goldenGooseFlag": false
          },
          "acctHubLinksPageBean": {
            "requestRefundLink": "#",
            "showUpdateContactInfoLink": false,
            "currentAPREnabledFlag": true,
            "showRequestRefundLink": false,
            "currentAPRLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=1&sorted_index=1&openLayer=A&intlink=us-ser-soa-accnthub-fin-currentapr",
            "showManageAcctAlertsLink": true,
            "payChargesOverTimeEnableFlag": false,
            "manageAcctAlertsLinkLabel": "Manage Account Alerts",
            "addCardforEmployeesLinkLabel": "",
            "yearEndSummaryLinkUrl": "#",
            "moreOptionsLinkLabel": "More Options",
            "showViewCreditScoreLink": true,
            "yearEndSummaryLinkLabel": "",
            "paymentSummaryLabel": "Payment Activity",
            "disputeOrInquireAbtChargeLink": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_disputes&intlink=us-ser-soa-accnthub-fin-disputesaboutacharge&entryChannel=ESTSM&locale=en_US&BPIndex=1&sorted_index=1",
            "viewCardMemberAgreementLink": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_pcm&sorted_index=1&intlink=us-ser-soa-accnthub-fin-cardagreement",
            "useFulLinkRowButtonLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&sorted_index=1&BPIndex=0&mycaTrend=YES&intlink=us-ser-soa-accnthub-serv-viewyearendsummarytrends",
            "addOthersToYourAccountLinkUrl": "https://www304.americanexpress.com/personal-card-application/supplementary/generic/apply/45263-9-0?intlink=us-ser-soa-accnthub-addsomeonetoyouraccount",
            "checkSpendingAbilityLinkLabel": "Check Spending Power",
            "searchPlacesToGoLinkUrl": "#",
            "viewCreditScoreLabel": "See FICO&reg; Credit Score",
            "currentAPRLabel": "Current APR",
            "replaceLostDamagedCardLinkLabel": "Replace Lost/Damaged Card",
            "showSearchPlacesToGoLink": false,
            "updateContactInfoLinkLabel": "",
            "showPaymentSummaryLink": false,
            "disputeOrInquireAbtChargeLabel": "Dispute/Inquire About a Charge",
            "viewCardMemberAgreementLabel": "Card Agreement",
            "useFulLinkRowTextLabel": "Year-End Summary is here! Now including new features.",
            "addCardforEmployeesLinkUrl": "#",
            "moreOptionsLinkUrl": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_home&Face=en_US&intlink=us-ser-soa-accnthub-serv-moreoptions",
            "requestRefundLabel": "",
            "viewCreditScoreLink": "https://online.americanexpress.com",
            "showSeeAllCardBenefitsLink": false,
            "viewCardMemberAgreementEnabledFlag": true,
            "showAddCardsForEmployeesLink": false,
            "showCheckSpendingAbilityLink": true,
            "useFulLinkRowButtonLabel": "View Now",
            "paymentSummaryLink": "https://online.americanexpress.com/myca/onlinepayment/us/paymenthistory.do?request_type=authreg_CardPayments&Face=en_US&sorted_index=1&intlink=us-ser-soa-accnthub-fin-paymentsummary",
            "seeAllCardBenefitsLinkUrl": "#",
            "showYearEndSummaryLink": false,
            "addOthersToYourAccountLinkLabel": "Add Someone to Your Account",
            "seeAllCardBenefitsLinkLabel": "",
            "searchPlacesToGoLinkLabel": "",
            "showReplaceLostDamagedCardLink": true,
            "requestRefundEnabledFlag": false,
            "showMoreOptionsLink": true,
            "replaceLostDamagedCardLinkUrl": "https://online.americanexpress.com/myca/accountprofile/us/view.do?request_type=authreg_ocr&sorted_index=1&source=janus&intlink=us-ser-soa-accnthub-serv-replacelostdamangedcard",
            "paymentSummaryEnabledFlag": true,
            "updateContactInfoLinkUrl": "#",
            "showAddOthersToYourAccountLink": true,
            "showGoPaperlessLink": true,
            "payChargesOverTimeLabel": "",
            "goPaperlessLinkLabel": "Go Paperless"
          },
          "limitsBean": {
            "increaseLineOfCreditLink": "https://online.americanexpress.com/myca/lineofcredit/us/action?request_type=authreg_LineOfCredit&sorted_index=1&intlink=us-ser-soa-accnthub-fin-requestcreditline",
            "availableCredit": "$5,798.00",
            "showSpendingLimitsData": false,
            "suppLimitsEnabled": false,
            "avlCrdtOffscrnTxt": "Your card has an Available Credit of $5,798.00",
            "nsplFlag": false,
            "suppIndicator": false,
            "availableCreditToolTipFlag": true,
            "needToSpendAboveCreditLinkLabel": "",
            "creditLimitLabel": "Credit Limit",
            "availableCreditLbl": "Available Credit",
            "increaseLineOfCreditLinkLabel": "Request Credit Line Increase",
            "limitsMsgFlag": false,
            "accessOtherCreditToolLink": "",
            "currentAboveLimitToolTipFlag": false,
            "needToSpendMoreLink": "",
            "accessOtherCreditToolLinkLabel": "",
            "limitMsgTooltip": "This amount is updated in real time and reflects all account activity, including outstanding authorizations. Since Recent Activity is updated nightly, it may not match this amount.",
            "transactionLimit": "Not Available",
            "limitsErrorMsgFlag": false,
            "totalCreditLimit": "$5,800.00",
            "noPreSetSpendingToolTip": ""
          },
          "financialBean": {
            "paymentsURL": "https://online.americanexpress.com/myca/onlinepayment/us/paymentcenter.do?request_type=authreg_PayBill&Face=en_US&sorted_index=1&intlink=us-ser-soa-accnthub-fin-makepayment",
            "postTransactionMsg": "It doesn't happen often, but your posted transactions are unavailable. Please try again later.",
            "paymentDueDateMsg": "Payment not required at this time",
            "corporateFootNote": "",
            "statementBalanceLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=1&sorted_index=1&intlink=us-ser-soa-accnthub-fin-statementbalance",
            "statementBalanceLbl": "Statement Balance",
            "recentPaymentsAndCredits": "$2,944.56",
            "payOverTimeUsefulLinkEligible": false,
            "currentBalanceLabel": "Remaining Statement Balance",
            "currentBalanceAmtHeader": "0",
            "seeAllRecentActivityLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=0&sorted_index=1&intlink=us-ser-soa-accnthub-trans-viewrecentactivity",
            "postTransactionErrorFlag": "true",
            "interestCalcLbl": "See APR History & Interest Charge Calculation",
            "stmtBalanceDateRange": "Mar 25 — Apr 22",
            "pendingChargesToolTip": "Pending Charges are purchases or pre-authorizations that haven't been posted to your account yet. For example, a hotel may pre-authorize an amount at check in, then submit the final charge at check out. Only the final charge will increase your Total Balance or accrue interest.",
            "hvolCard": false,
            "recentsPmtCreditsLbl": "Recent Payments & Credits",
            "paymentMsg": "Minimum Payment Due",
            "aprStmtEndDate": "April 22",
            "goToOnlineStatmentLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=1&sorted_index=1&intlink=us-ser-soa-accnthub-trans-currentstatement",
            "currentBalance": "$0.00",
            "outstandingAmtDecimal": "43",
            "recentActivityLink": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=0&sorted_index=1&intlink=us-ser-soa-accnthub-fin-recentactivity",
            "currentBalanceDot": ".",
            "currentBalanceAmtCents": "00",
            "nextStmtClosingDate": " (Next Closing Date May 24)",
            "outstandingAmtDollar": "$",
            "displayPaymentReminderMsg": true,
            "pendingChargesFlag": true,
            "recentPaymentAndCreditsToolTip": "This amount includes any payments, returned payments and credits received since your most recent billing statement. Activity in the last 24 hours may not be reflected.",
            "totalTransactionCount": -1,
            "statementBalanceToolTip": "This amount is the New Balance showing on your most recent billing statement. This balance does not include any new payments, returned payments, credits or transactions made after the last closing date.  No amounts under dispute have been deducted from this balance.",
            "displayPaymentDueDate": false,
            "currentBalanceDollar": "$",
            "currentBalanceToolTip": "This amount is the New Balance showing on your most recent billing statement adjusted for payments, returned payments and applicable credits since your last statement closing date. Any amounts under dispute have been deducted from this balance.",
            "outStandingBalanceToolTip": "This amount is the full balance on your account adjusted for payments, returned payments, applicable credits and transactions since your last statement closing date. No amounts under dispute have been deducted from this balance. Activity in the last 24 hours may not be reflected.",
            "recentPaymentsLink": "https://online.americanexpress.com/myca/estmt/us/list.do?Face=en_US&request_type=authreg_Statement&sorted_index=1&BPIndex=0&applyFilter=true&transactionTypeFilter=4,5&intlink=us-ser-soa-accnthub-fin-recentpaymentsandcredits",
            "minPaymentDueToolTip": "This amount refers to the minimum payment required to keep your account current. You may still incur interest on any unpaid portion of your Remaining Statement Balance.",
            "postedTransactionToolTip": "Charges, payments, and credits since your statement closed on Apr 22.",
            "recentActivityDateRange": "Apr 23 — Today (Next Closing Date May 24)",
            "paymentsLabel": "Make Payment",
            "downloadStatement": "https://online.americanexpress.com/myca/statementimage/us/welcome.do?Face=en_US&request_type=authreg_StatementCycles&sorted_index=1&intlink=us-ser-soa-accnthub-fin-billingstatements",
            "paymentReminderMsg": "",
            "recentActivityLbl": "Recent Activity",
            "suppIndicator": false,
            "pleasePayByToolTip": "",
            "interestCalcURL": "https://online.americanexpress.com/myca/estmt/us/list.do?request_type=authreg_Statement&Face=en_US&BPIndex=1&sorted_index=1&openLayer=A",
            "negativeCurrBalText": "",
            "smallChnlPmtDueDate": "Not Available",
            "recentActivityDate": " since Apr 23",
            "paymentDueDate": "",
            "currentStatementLbl": "Current Statement",
            "corporateFootNoteSuperScript": "",
            "displayPayoverTimeLink": false,
            "simplyCashBizOverLimitIndicator": false,
            "outstandingBalance": "$1.43",
            "paymentAmt": "$0.00",
            "recentCharges": "$1,701.06",
            "requestRefundEnabledFlag": false,
            "currentBalOffscrnTxt": "Your card has a Remaining Statement Balance of 0 dollars and 00 cents ",
            "statementBalance": "$1,244.93",
            "viewAllRecentActivityLbl": "View All Recent Activity",
            "displayCurrentAPRLinkFlag": true,
            "currentBalanceLblForShowEqnToolTip": "This amount is the New Balance showing on your most recent billing statement adjusted for payments, returned payments and applicable credits since your last statement closing date. Any amounts under dispute have been deducted from this balance.",
            "outstandingBalanceLbl": "Total Balance",
            "billingStatementsLbl": "Billing Statements",
            "currentBalanceLblForShowBalanceEqn": "Remaining Statement Balance",
            "recentActivityToolTip": "This amount includes all charges, excluding credits, payments, and returned payments, since your most recent billing statement. Activity in the last 24 hours may not be reflected.",
            "outstandingAmtHeader": "1",
            "displayDisputeMsg": false
          },
          "goldenGooseFlag": false,
          "membershipRewardsBean": {
            "loyaltyEarninginstrumentListCount": 0,
            "deltaToolTip": "This amount reflects your full available SkyMiles account balance, which includes miles earned with your Card through your last statement balance.",
            "usePointsForShoppingLabel": "",
            "eligibleForDPM": false,
            "ctaButtonLargeLink": "http://www.delta.com/skymiles/use_miles/index.jsp",
            "errorFlag": false,
            "plumSupp": false,
            "multiLnkIndActiveAccntIndicator": false,
            "usePointsForGiftCardsLabel": "",
            "loyaltyAccountNumberLabel": "SkyMiles#",
            "noLoyaltyCTALink": "#",
            "mrDataAvailableFlag": true,
            "availablePointsLink": "#",
            "pointBalanceLabel": "Available Miles",
            "noLoyaltyCTALabel": "",
            "usePointsForInvestWithRewardsLabel": "",
            "moreInfoLinkLrgURL": "#",
            "pointBalance": "10,131",
            "openRebateCardWithNoCta": false,
            "moreInfoLinkLrgTxt": "",
            "membershipRewardsProgNameLink": "#",
            "programName": "Delta SkyMiles&reg;",
            "loyaltyAccountNumber": "9412652332",
            "ctaButtonLabel": "Use Miles",
            "errorMessage1": "Sorry about that!",
            "usePointsForTravelLink": "#",
            "errorMessage2": "It doesn't happen often, but your Rewards information is unavailable.",
            "usePointsForChargesLabel": "",
            "errorMessage3": "Please try again later.",
            "loyaltyResponseCode": "LAI0000",
            "jetBlueCardProductFlag": false,
            "goldenGooseMREligibleFlag": false,
            "freedomPassCardProduct": false,
            "loyaltyProgramType": "COBRAND_PROGRAMS",
            "usePointsForChargesLink": "#",
            "medallionStatusToolTip": "Medallion status is based on the latest information provided by Delta, which may not be real-time. For real-time information, visit Delta.com or call Delta.",
            "nonMRFlag": true,
            "buckChargeCard": false,
            "usePointsForShoppingLink": "#",
            "rewardsForPlumPresent": false,
            "buckLendingCard": false,
            "loyaltyTier": "GC",
            "usePointsLabel": "",
            "loyaltyFamily": "Delta",
            "usePointsForGiftCardsLink": "#",
            "pointsYTDLabel": "",
            "loyaltyOfferLink": "http://www.membershiprewards.com/homepage.aspx?intlink=CMO_newSOA_MR",
            "noLoyaltyFlag": false,
            "waysToUsePointsText": "",
            "loyaltyStatus": "",
            "moreInfoLinkSmlURL": "#",
            "usePointsForTravelLabel": "",
            "moreInfoLinkSmlTxt": "",
            "pendingPointsMobLink": "#",
            "loyaltyStatusFlag": false,
            "noLoyaltyMessage1": "",
            "noLoyaltyMessage2": "",
            "plumBasic": false,
            "ctaButtonLargeLabel": "Use Miles",
            "ctaButtonLink": "https://m.delta.com"
          },
          "acctLevelMsgPageBean": {
            "incomeCaptureMsgFlag": false,
            "sixtyDaysPastDueMessage": "",
            "openCardFlag": false,
            "repetitiveNFCFlag": false,
            "warnMsgFlag": false,
            "nfcFlag": false,
            "displaySixtyDaysPastDueMsg": false,
            "displayOffersTab": false,
            "acctLevelNFCMessage": ""
          }
        }
      ],
      "AccMgmtUserProfileList": [
        {
          "oceEnableFlag": false,
          "aprErrorMsgLine1": "Sorry about that!",
          "simplyCashDeepLinkEnabled": false,
          "aprErrorMsgLine2": "It doesn't happen often, but your APR information is unavailable.",
          "updatePrefAjaxURL": "/myca/accountsummary/us/updatePreference?request_type=authreg_acctAccountSummary&Face=en_US",
          "aprErrorMsgLine3": "Please try again later.",
          "postedTxnAjaxURL": "/myca/accountsummary/us/postedtxn?request_type=authreg_acctAccountSummary&Face=en_US",
          "onLoadAjaxURL": "/myca/accountsummary/us/onLoadData?request_type=authreg_acctAccountSummary&Face=en_US",
          "showPendingChargesDeeplink": false,
          "isLandingFromLogon": "false",
          "eosAddToCardAjaxURL": "/myca/accountsummary/us/eosUpdateOffer.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "aprAjaxURL": "/myca/accountsummary/us/viewApr.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "memberSinceDate": "CARD MEMBER SINCE 2013",
          "eosSelectedOfferContentAjaxURL": "/myca/accountsummary/us/eosSelectedOfferContent.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "openPaymentPathSrcCode": "CM7",
          "aprHeader": "Annual Percentage Rates",
          "ytdMRPoints": "Not Available",
          "eosAvailableOfferContentAjaxURL": "/myca/accountsummary/us/eosOfferContent.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "environment": "E3_PROD",
          "openSavingsExpPrgmPrtnrLink": "#",
          "postedTransErrorMsg": "It doesn't happen often, but your posted transactions are unavailable. Please try again later.",
          "oceOmnTrackingText": "",
          "accountHomeUrl": "https://online.americanexpress.com/myca/accountsummary/us/accounthome?request_type=authreg_acctAccountSummary&Face=en_US",
          "stopOnloadAjaxCall": false,
          "origin": "janus",
          "warnMsgFlag": false,
          "openSavingsLbl": "",
          "relationshipLevelNFCMessage": "",
          "viewOffersFlag": false,
          "oceCardArtURL": "",
          "openSavingsExpPrgmLink": "#",
          "ytdMembershipRewardsLbl": "YTD Membership Rewards",
          "eosAvailableOffersAjaxURL": "/myca/accountsummary/us/myOffers.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "mrPendingPointsAjaxURL": "/myca/accountsummary/us/mrPendingPoints.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "oceMessage1": "",
          "openSavingsExpPrgmPrtnrLinkLbl": "",
          "oceMessage2": "",
          "oceMessage3": "",
          "eosOfferSavingAjaxURL": "/myca/accountsummary/us/eosSavedOffer.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "openSavingsAmount": "Not Available",
          "offerDtlsDeepLinkEnabled": false,
          "pendingTransErrorMsg": "It doesn't happen often, but your pending charges are unavailable. Please try again later.",
          "selectedCardSortedIndex": 0,
          "ytdDiscountLbl": "YTD Discount",
          "showOpenPaymentPathLayer": false,
          "encryptedAcctNumList": [
            "O5C1l-wfCI7BExwokGSyoVem9EmSsrX0_kjdBdJAehk=",
            "O5C1l-wfCI7BExwokGSyoWHT-ojrc7B6-acLbstTUYM="
          ],
          "killSwitchEntriesBean": {
            "goldenGooseKillEnabled": false,
            "postedTransactionKillEnabled": false,
            "lssPendingPointsKillEnabled": false,
            "eosSelectedOffersKillEnabled": false,
            "pznOffersKillEnabled": false,
            "eosUpdateOfferKillEnabled": false,
            "eosSummaryAvlbleOffersKillEnabled": false,
            "pendingChargesKillEnabled": false,
            "lssJetBlueKillEnabled": false,
            "eosSavingsSummaryKillEnabled": false,
            "eosSavingsHistoryKillEnabled": false
          },
          "showEducationalLayer": false,
          "enableOpenSavingsMRBlock": false,
          "pendingTxnAjaxURL": "/myca/accountsummary/us/pendingtxn.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "enterpriseSelectedOffersAjaxURL": "/myca/accountsummary/us/eosSelectedOffers.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "hasOpenSavingsData": false,
          "onlyCancelOrCorpOrCPC": false,
          "oceDisplayIndex": -1,
          "openSavingsExpPrgmLinkLbl": "",
          "oceCardMemberName": "",
          "displayFicoOptIn": false,
          "publicGUID": "5fca9fb83644a3546d6dab002bb3d20b",
          "pznTrackingURL": "https://www251.americanexpress.com/personalization/v1/treatments/customers/events/",
          "paymentStatusAjaxURL": "/myca/accountsummary/us/paymentstatus.do?request_type=authreg_acctAccountSummary&Face=en_US",
          "touchEnabledDevice": false,
          "lastLogonDate": "May 18, 2016 @ 3:51 PM ET"
        }
      ]
    }
  }

  addNodeToObject = (key, value, keyPath) => {
    let path = [key, ...keyPath].reverse();
    let dotPath = path.join('.');
    //assign new key ass unique
    this.setState(DotObject.copy('value', dotPath, { value }, this.state));
  };

  removeNodeFromObject = (keyPath) => {
    let path = [...keyPath].reverse();
    let dotPath = path.join('.');
    let stateCopy = Object.assign({}, this.state);
    //let newObj = DotObject.pick(dotPath, this.state, true);
    DotObject.remove(dotPath, stateCopy);
    //console.log(newObj);
    this.setState(stateCopy);
  };

  updateNodeValue = (value, keyPath) => {
    let path = [...keyPath].reverse();
    let dotPath = path.join('.');
    this.setState(DotObject.copy('value', dotPath, { value }, this.state));
  };

  updateNodeKey = (newKey, keyPath) => {
    let path = [...keyPath].reverse();
    let dotPath = path.join('.');
    let value = DotObject.pick(dotPath, this.state, true);
    path[path.length - 1] = newKey;
    let newDotPath = path.join('.');
    this.setState(DotObject.copy('value', newDotPath, { value }, this.state));
  };


  render() {
    return (
      <div>
        <pre>{JSON.stringify(this.state)}</pre>
        <JSONTree data={this.state}
                  updateValue={this.updateNodeValue}
                  updateNodeKey={this.updateNodeKey}
                  removeNode={this.removeNodeFromObject}
                  addNode={this.addNodeToObject} hideRoot={true} />
      </div>
    )
  }
}
